#!/bin/bash
set -e -x
main(){
	for d in /var/lib/mupif/{mupif-git,mupifDB,monitor}; do
	    git -C $d pull --ff
	    python3 -m pip install -r $d/requirements.txt
	done
        supervisorctl restart ex13 mupifdb-REST mupifdb-web mupifdb-fastapi mupif-monitor
	sleep 2
        supervisorctl restart mupifdb-scheduler
	sleep 3
        supervisorctl status
}
main | ccze -A
